include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_double_quotes: true

analyzer:
  errors:
    todo: ignore
  language:
    strict-casts: true
    strict-raw-types: true